#Makefile for linux

PING_SRC=${../src}

BUILD_DIR = ${PWD}/build



# TODO Make a proper Makefile
build/ping1d-simple: 
	g++ ./ping1d-simple/ping1d-simple.cpp	../src/*.cpp -std=c++11 -I ../src -o build/ping1d-simple



